-- citron-theme (https://github.com/kiwec/vis-citron)

local lexers = vis.lexers
lexers.STYLE_DEFAULT = 'fore:#ffffff,back:#1c1c1c'
lexers.STYLE_NOTHING = ''
lexers.STYLE_CLASS = ''
lexers.STYLE_COMMENT = 'fore:#00cd00'
lexers.STYLE_CONSTANT = 'fore:#f26213'
lexers.STYLE_DEFINITION = 'fore:#aa0000'
lexers.STYLE_ERROR = 'fore:#f2131b,bold'
lexers.STYLE_FUNCTION = 'fore:#ffd700'
lexers.STYLE_KEYWORD = 'fore:#ffd700'
lexers.STYLE_LABEL = 'fore:#ffd700'
lexers.STYLE_NUMBER = 'fore:#f26213'
lexers.STYLE_OPERATOR = 'fore:#ffd700'
lexers.STYLE_REGEX = ''
lexers.STYLE_STRING = 'fore:#00cdcd'
lexers.STYLE_PREPROCESSOR = 'fore:#aaaaaa'
lexers.STYLE_TAG = ''
lexers.STYLE_TYPE = 'fore:#ffd700'
lexers.STYLE_VARIABLE = 'fore:#8dfa00'
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = ''
lexers.STYLE_IDENTIFIER = 'fore:#ffffff'

lexers.STYLE_LINENUMBER = 'back:#3a3a3a'
lexers.STYLE_LINENUMBER_CURSOR = 'back:#444444'
lexers.STYLE_CURSOR = 'fore:#000000,back:#e4cd43'
lexers.STYLE_CURSOR_PRIMARY = 'back:#e4cd43'
lexers.STYLE_CURSOR_LINE = 'back:#262626'
lexers.STYLE_COLOR_COLUMN = 'back:#262626'
lexers.STYLE_SELECTION = 'fore:#000000,back:#e4cd43'
lexers.STYLE_STATUS = 'fore:#000000,back:#ffd700'
lexers.STYLE_STATUS_FOCUSED = 'fore:#000000,back:#ffd700'
lexers.STYLE_SEPARATOR = ''
lexers.STYLE_INFO = ''
lexers.STYLE_EOF = ''

